apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: feedback-form-pipeline-run-
  namespace: deep-dive-kafka
spec:
  params:
    - name: git-url
      value: 'https://github.com/marcoklaassen/deep-dive-serverless-feedback-form'
    - name: git-revision
      value: kafka-deep-dive
    - name: IMAGE
      value: >-
        image-registry.openshift-image-registry.svc:5000/deep-dive-quarkus/feedback-form
    - name: APPVERSION
      value: 0.1
  pipelineRef:
    name: quarkus-native-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi