apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: feedback-form-pipeline-run-
  namespace: serverless-demo
spec:
  params:
    - name: git-url
      value: 'https://github.com/marcoklaassen/deep-dive-serverless'
    - name: git-revision
      value: main
    - name: IMAGE
      value: >-
        image-registry.openshift-image-registry.svc:5000/serverless-demo/feedback-form
    - name: DOCKERFILE
      value: feedback-form/src/main/docker/Dockerfile.native
    - name: APPVERSION
      value: latest
    - name: workingDir
      value: /feedback-form
  pipelineRef:
    name: quarkus-native-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi